FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    can-utils \
    iproute2

WORKDIR /app

COPY common/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["bash"]
